# Example environment configuration for QA Brother
# Copy this to your Streamlit Cloud secrets (not as a file)

FIGMA_ACCESS_TOKEN = "your_figma_token_here"
JIRA_SERVER_URL = "https://your-company.atlassian.net"
JIRA_EMAIL = "your-email@company.com"
JIRA_API_TOKEN = "your_jira_token_here"
JIRA_PROJECT_KEY = "QA"
OPENAI_API_KEY = "sk-your_openai_key_here"
GROQ_API_KEY = "gsk_your_groq_key_here"
GROQ_MODEL = "llama-3.1-8b-instant"

# Optional: Default test URLs
WEB_TEST_URL = "https://your-test-site.com"
FIGMA_FILE_KEY = "your_default_figma_file_key"

# Logging
LOG_LEVEL = "INFO"
