# Streamlit Cloud Secrets Configuration Template
# Copy this template and fill in your actual API keys

[api_keys]
openai_api_key = "sk-proj-YOUR-OPENAI-KEY-HERE"
groq_api_key = "gsk_YOUR-GROQ-KEY-HERE"
figma_token = "figd_YOUR-FIGMA-TOKEN-HERE"

[jira]
server_url = "https://your-domain.atlassian.net"
username = "your-email@domain.com"
api_token = "YOUR-JIRA-API-TOKEN-HERE"
project_key = "YOUR-PROJECT-KEY"

# Top-level secrets (alternative format)
FIGMA_ACCESS_TOKEN = "figd_YOUR-FIGMA-TOKEN-HERE"
FIGMA_FILE_KEY = "YOUR-FIGMA-FILE-KEY"
FIGMA_TEST_URL = "https://www.figma.com/design/YOUR-FILE-KEY/Your-Design"
WEB_TEST_URL = "https://your-website.com"
JIRA_SERVER_URL = "https://your-domain.atlassian.net"
JIRA_EMAIL = "your-email@domain.com"
JIRA_API_TOKEN = "YOUR-JIRA-API-TOKEN-HERE"
JIRA_PROJECT_KEY = "YOUR-PROJECT-KEY"
OPENAI_API_KEY = "sk-proj-YOUR-OPENAI-KEY-HERE"
GROQ_API_KEY = "gsk_YOUR-GROQ-KEY-HERE"
GROQ_MODEL = "llama-3.1-8b-instant"
LOG_LEVEL = "INFO"
